import FreeSimpleGUI as sg

def layout_window1():
    layout_one = [[sg.Push(background_color='light grey'),
                   sg.Text("Welcome!",
                           text_color='black',
                           auto_size_text=True,
                           font=('Arial', 20),
                           background_color='light grey'),
                   sg.Push(background_color='light grey')],
                  [sg.Push(background_color='light grey'),
                   sg.Text('Press "Begin" to start calibration.',
                           text_color='black',
                           font=('Times New Roman', 16),
                           background_color='light grey'),
                   sg.Push(background_color='light grey')],
                  [sg.Text(" ", background_color='light grey')],
                  [sg.Push(background_color='light grey'),
                   sg.Button('Begin',
                             font=('Helvetica', 16)),
                   sg.Push(background_color='light grey')],
                  [sg.Push(background_color='light grey'),
                   sg.Text(key='-INTRO-',
                           font=('Times New Roman', 16),
                           text_color='black',
                           background_color='light grey'),
                   sg.Push(background_color='light grey')],
                  [(sg.Push(background_color='light grey'),
                    sg.Text(key='-DIGIT_ONE-',
                            text_color='black',
                            font=('Times New Roman', 14),
                            background_color='light grey'),
                    sg.Text(key='-P1-',
                            text_color='black',
                            background_color='light grey'),
                    sg.Text(key='-P2-',
                            text_color='black',
                            background_color='light grey'),
                    sg.Text(key='-P3-',
                            text_color='black',
                            background_color='light grey'),
                    sg.Text(key='-DIGIT_TWO-',
                            text_color='black',
                            font=('Times New Roman', 14),
                            background_color='light grey'),
                    sg.Text(key='-P4-',
                            text_color='black',
                            background_color='light grey'),
                    sg.Text(key='-P5-',
                            text_color='black',
                            background_color='light grey'),
                    sg.Text(key='-P6-',
                            text_color='black',
                            background_color='light grey'),
                    sg.Text(key='-DIGIT_THREE-',
                            text_color='black',
                            font=('Times New Roman', 14),
                            background_color='light grey'),
                    sg.Push(background_color='light grey'))]
                  ]
    return layout_one